INSERT INTO midrash_list (`group`, seed, short_desc, long_desc, source) VALUES
-- Group A
('A', 1, 'The Mann\'s taste', 'The Mann tasted like whatever you wanted it to taste like', 'Yoma 75a'),
('A', 2, 'Yaakov, Serach, and the harp', 'Serach bas Asher was the one to tell Yaakov that Yosef was still alive and played a harp to do so', 'Targum Yonason Beraishis 46/17; Sefer HaYashar'),
('A', 3, 'How Makkas Tzefardeia began', 'Makkas Tzefardeia started with one giant frog. When the Mitzrim would hit the frog, it spit out many other, smaller frogs', 'Tanchuma Va\'eira 14; Tosafos al HaTorah'),
('A', 4, 'Makkas Dam same cup phenomenon', 'During Makkas Dam, if a Jew and Mitzri would drink from the same cup, the Jew would drink water while the Mitzri would get blood', 'Shemos Rabba 9/10'),
('A', 5, 'Showing the Torah to the nations', 'Before Mattan Torah, a Malach showed the Torah to the nations asking them if they wanted to accept it. They refused due to certain Mitzvos', 'Sifri V\'zos Haberacha'),
('A', 6, 'Adam and Chava\'s burial', 'Adam and Chava are buried in Me\'aras HaMachpeila', 'Beraishis Rabba 58/4'),
('A', 7, 'Avram\'s and Lot\'s sheperd\'s fight', 'Avram\'s and Lot\'s sheperds fought about whether or not to muzzle their animals (to prevent them from grazing in others\' fields)', 'Beraishis Rabba 41/5'),
('A', 8, 'Sarah in a box', 'Avram put Sarah in a box when they came to Mitzrayim', 'Beraishis Rabba 40/6'),
('A', 9, 'The especially hot day', 'Hashem made it extra hot on the day that He visited Avraham', 'Bava Metzia 86b'),
('A', 10, 'Dassan and Aviram fighting', 'Dassan and Aviram were the people fighting whom Moshe stopped', 'Nedarim 64b'),
('A', 11, 'The Keruvim had children\'s faces', 'The Keruvim had children\'s faces (one boy and one girl)', 'Zohar Chadash Teruma 54a'),
('A', 12, 'Mitzri magicians by Makkas Kinim', 'The Mitzri magicians weren\'t able to replicate Makkas Kinim because their magic couldn\'t deal with anything smaller than a barley kernel', 'Shemos Rabba 10/7'),
('A', 13, 'Dinah in a box', 'Yaakov put Dinah in a box so Eisav couldn\'t see her', 'Beraishis Rabba 77/3'),
('A', 14, 'Yosef\'s extra jail time', 'Yosef had to stay in jail for an extra two years due to his over-trusting in the Sar HaMashkim to get him out', 'Beraishis Rabba 89/3'),
('A', 15, '12 paths in the Yam Suf', 'The Yam Suf split into twelve paths, one for each Shevet', 'Mechilta Beshalach 4'),
('A', 16, 'How Moshe killed Og', 'Moshe took a ten amah ax, jumped ten amos in the air, only reached Og\'s ankle, but was still able to kill him', 'Berachos 54b'),

-- Group B
('B', 1, 'Basya\'s long hand', 'Basya\'s arm elongated so she could reach Moshe\'s basket', 'Sotah 12a'),
('B', 2, 'Makkas Choshech treasure hunt', 'During Makkas Choshech, Bnei Yisrael searched through the Mitzrim\'s houses to see where they hid their treasures to ask about them later', 'Shemos Rabba 14/3'),
('B', 3, 'Yaakov and Eisav in womb', 'While they were in the womb, Yaakov tried to get out when Rivka would pass a Beis Medrash while Eisav tried to get out when she would pass a Beis Avoda Zara', 'Beraishis Rabba 63/6'),
('B', 4, 'Yaakov\'s stone pillow', 'The twelve stones that Yaakov put under his head when he went to sleep merged into one large stone', 'Chulin 91b'),
('B', 5, 'Shifra and Puah\'s identities', 'Shifra was Yocheved; Puah was Miriam', 'Sotah 11b'),
('B', 6, 'Six babies at once', 'Bnei Yisrael had six babies at a time while in Mitzrayim', 'Shemos Rabba 1/8'),
('B', 7, 'Naaseh V\'nishma crowns', 'Bnei Yisrael received crowns when they said Naaseh V\'nishma', 'Shabbos 88a'),
('B', 8, 'Har Sinai like a barrel', 'Hashem held Har Sinai over Bnei Yisrael like a barrel to force them to accept the Torah', 'Shabbos 88a'),
('B', 9, 'Paroh in pajamas', 'Paroh ran through Goshen (in his pajamas) to find Moshe during Makkas Bechoros and got lost', 'Mechilta Bo 13'),
('B', 10, 'Which Malachim visited Avraham', 'Which three Malachim visited Avraham and what their jobs were (Michael to inform Avraham and Sarah about Yitzchok\'s upcoming birth, Gavriel to destroy Sedom, and Refael to heal Avraham from his milah and save Lot from Sedom)', 'Bava Metzia 86b'),
('B', 11, 'When Parshas Vayeira starts', 'Parshas Vayeira begins on the third day after Avraham\'s milah', 'Bava Metzia 86b'),
('B', 12, 'Three miracles in Sarah\'s tent', 'There were three constant miracles in Sarah\'s tent: the challah stayed fresh throughout the week, the candles stayed lit, and the cloud of the Shechina hovered over the tent', 'Beraishis Rabba 60/16'),
('B', 13, 'Yosef\'s wagons', 'Yosef sent wagons to Yaakov to tell him that he remembered that they were learning about Egla Arufa before he left', 'Beraishis Rabba 94/3'),
('B', 14, 'Yocheved\'s birthplace', 'Yocheved was born at the Mitzri border; she was the 70th person to come down to Mitzrayim', 'Bava Basra 123b'),
('B', 15, 'Avraham discovered Hashem at three', 'Avraham discovered Hashem when he was three years old', 'Beraishis Rabba 30/8'),
('B', 16, 'Hagar\'s lineage', 'Hagar was Paroh\'s daughter', 'Beraishis Rabba 45/1'),

-- Group C
('C', 1, 'Yaakov\'s wrestling partner', 'Yaakov wrestled with Eisav\'s Malach', 'Beraishis Rabba 77/3'),
('C', 2, 'Avram in Ur Kasdim', 'The whole story of Avram destroying Terach\'s idols and getting thrown in the furnace', 'Beraishis Rabba 38/13'),
('C', 3, 'Avraham\'s tent\'s doors', 'Avraham\'s tent had four doors, one in each direction, to welcome guests from everywhere', 'Midrash Tehilim 110'),
('C', 4, 'Why Yaakov recrossed the river', 'Yaakov went back over the river to pick up pachim ketanim', 'Chulin 91a'),
('C', 5, 'Where Yaakov slept', 'Yaakov slept on Har Hamoriah (where he dreamed about the ladder)', 'Yalkut Shimoni 107'),
('C', 6, 'Mitzrim getting water by Makkas Dam', 'The Mitzrim were able to buy water from Bnei Yisrael during Makkas Dam making the Jews very rich', 'Shemos Rabba 9/10'),
('C', 7, 'How Sarah died', 'Sarah died after hearing about the Akeida', 'Tanchuma Vayeira 23'),
('C', 8, 'Simultaneous Zachor and Shamor', 'Zachor and Shamor were spoken at the same time', 'Yalkut Shimoni 293'),
('C', 9, 'Why Yehuda was sent ahead to Goshen', 'Yaakov sent Yehuda ahead to Goshen to build a Beis Midrash there', 'Beraishis Rabba 95/3'),
('C', 10, 'Besuel tried to poison Eliezer', 'Besuel tried to poison Eliezer but a Malach switched the plates and Besuel died', 'Yalkut Shimoni 109'),
('C', 11, 'Protection from the Ananei HaKavod', 'The Ananei HaKavod repelled weapons shot at Bnei Yisrael', 'Mechilta D\'Rabi Yishmael Beshalach 5/5'),
('C', 12, 'Yaakov by Shem V\'Ever', 'Yaakov studied at Yeshivas Shem V\'Ever for fourteen years before going to Charan', 'Megilla 16b'),
('C', 13, 'Yaakov\'s shortened lifespan', 'Yaakov lost thirty three years of his life for complaining to Paroh', 'Midrash Aggada Vayigash 47/28'),
('C', 14, 'Yaakov said Sh\'ma', 'Yaakov was saying Sh\'ma when he met Yosef', 'Midrash Aggada Vayigash 46/29'),
('C', 15, 'Ten creations during Beis Hashmashos', 'Hashem created ten special things during Bein Hashmashos after the sixth day of creation', 'Avos 5/9'),
('C', 16, 'Yaakov wanted to reveal the "keitz"', 'Yaakov wanted to reveal the "keitz" to his children but was unable and they said Sh\'ma to reassure him of their Emunah', 'Beraishis Rabba 98/3'),

-- Group D
('D', 1, 'Rachel gave simanim to Leah', 'Rochel gave the simanim to Leah so she wouldn\'t be embarrassed in public under the chuppah with Yaakov', 'Bava Basra 123a'),
('D', 2, 'Snakes with Yosef in the pit', 'There were snakes and scorpions in the pit with Yosef', 'Shabbos 22a'),
('D', 3, 'The Teiva\'s floor\'s contents', 'What was on each floor of the Teivah: people on top, animals in the middle, and the garbage on the bottom', 'Sanhedrin 108a'),
('D', 4, 'Sar HaMashim and Sar HaOfim\'s crimes', 'Why the Sar HaMashkim and Sar HaOfim were put in jail: a fly in the wine and a stone in the bread', 'Beraishis Rabba 88/2'),
('D', 5, 'The moon complained and was shrunk', 'The moon complained about being the same size as the sun so Hashem shrank it', 'Chulin 60b'),
('D', 6, 'Nachshon was first in the Yam Suf', 'Nachshon ben Aminadav was the first person to jump into the Yam Suf', 'Yalkut Shimoni 234'),
('D', 7, 'The well water rose to Rivka', 'The water in the well rose to Rivka when she came to fill her pitcher', 'Beraishis Rabba 60/5'),
('D', 8, 'Og survived the Mabul', 'Og survived the Mabul; he was either in or outside the Teiva', 'Zevachim 113b'),
('D', 9, 'Rivka married Yitzchok at three', 'Rivka married Yitzchok when she was three years old', 'Yalkut Shimoni 110'),
('D', 10, 'Yosef saw Yaakov\'s D\'mus D\'yoken', 'Yosef saw the "D\'mus D\'yoken" of Yaakov which helped him overcome Eishes Potiphar', 'Sotah 36b'),
('D', 11, 'Yaakov and Eisav in Yitzchok\'s tent', 'Eisav was entering Yitzchok\'s tent to receive the beracha at the exact moment that Yaakov was leaving', 'Beraishis Rabba 66/5'),
('D', 12, 'How Moshe\'s mouth got ruined', 'Moshe stole Paroh\'s crown as a baby so they tested him with jewels and coals to see what he reached for and he put the coal in his mouth, burning it', 'Shemos Rabba 1/26'),
('D', 13, 'Eisav trying to bite Yaakov\'s neck', 'Eisav tried to bite Yaakov\'s neck but it turned to stone and Eisav lost his teeth', 'Beraishis Rabba 78/9'),
('D', 14, 'Noach and the lion', 'One day Noach was late in bringing the lion\'s food so it hit him, injuring him', 'Tanchuma Noach 9'),
('D', 15, 'Global Kerias Yam Suf', 'All the water in the world split during Kerias Yam Suf', 'Shemos Rabba 21/6'),
('D', 16, 'Birds ate the Mann', 'Birds ate the Mann that Dassan and Aviram put out on Shabbos (to try to prove that the Mann did fall on Shabbos)', 'Taamei HaMinhagim, Inyanim Shonim 98');